### ISSUE TITLE
ChatBot

### ISSUE THREAD

**Issue by VeteranSoftDev** [DedicatedSoftwareDev/Lending-Bot#16]
### Discussed in https://github.com/DedicatedSoftwareDev/Lending-Bot/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **DedicatedSoftwareDev** February 20, 2024</sup>
How to create chatbot and connect to telegram?</div>

**Comment by DedicatedSoftwareDev** [comment]
You idea is unique and new for this project. I will consider about your professional opinion carefully.
Thank you.
